### ISSUE TITLE
There is some application error in the website. Urgent!!!

### ISSUE THREAD

**Issue by raj03kumar** [NUMBART/leetboard#2]

**Comment by raj03kumar** [comment]
Application error
An error occurred in the application and your page could not be served. If you are the application owner, [check your logs for details](https://devcenter.heroku.com/articles/logging#view-logs). You can do this from the Heroku CLI with the command
heroku logs --tail

**Comment by NUMBART** [comment]
redeployed to https://leeter-board.web.app/
